# Install script for directory: /home/spiff/kode/visualization.projectm/lib/libprojectM

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/home/spiff/kode/visualization.projectm/lib/libprojectM/NONE")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "None")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/spiff/kode/visualization.projectm/lib/libprojectM/NONE/share/projectM/presets" TYPE FILE FILES
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Anomalous Material Science (Pure Splinter Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Approach (Vectrip Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo (Demonology Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Eddies 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Mstress - Snowing Fiber City.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - The Awakening.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - French Clothing.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Kalideostars (Altars Of Madness MIx).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Churn.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Round and Round (geiss gamma mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Paranormal Static.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness 4 (Spirit Of Twisted Madness M.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - City Helix Lattice.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Oozing Resistance.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic Aderrasi & nil - LA movement (Intellectual Sens.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - glowsticks v2 04 music minimal.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirl 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic - Harmonic Bliss (elated mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Contortion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Can't Stop the Blithering.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/che - adela the flower.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Idiot - ATan2 Demo (Spiraling Mad Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Ether Storm.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic & Unchained - Minor Alteration.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Making a Science of It 4.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Elastoid.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Window Reflection 6.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Two-Pointed Pulsagon.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirlie 4.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - LabFunk.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Luckless.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Anomaly 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Touchdown on Mars (Detailed Pictures Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/TobiasWolfBoi - Cataract.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Space Voyage Bright.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Mysticial Awakening Mi.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - glowsticks v2 05 and proton lights (+Krash's beat code) _Phat_remix07 recursive demons.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Illusion - Spiral Movement.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Solarized Space.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Hyperspace.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Texture Boxes (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Agitator.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot & Rovastar - Altars Of Madness 2 (X.42 Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Dynamic Fractal 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cycloid 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Trampoline.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Illusion - Dual Wave 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - What Is.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Rocke - Sugar Spun Sister.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 2.1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Slow Shift Matrix (Ethereal Drift).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus Ever Changing.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Chemical Spirituality.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Omnipresence Resurrection.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Flotsam.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Causeway Of Dreams (REMix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Housed In A Childish Mind.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - 3D Shapes Demo 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 2.0.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Space Voyage (High-Warp).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - In Memory Of Peg.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Lost Souls of the Bermuda Triangle (Darkest Soul.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Fractopia (Fantic Dancing Lights Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 10.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Goofy Beat Detection.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Bmelgren & Krash - Rainbow Orb Peacock (Centred Journey Mix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Heavenly 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bipolar 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/baked - mushroom rainbows[2].milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Puddle Of Music.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Rainbow Planet Under Attack.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot24-7 - Ascending to heaven 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Inner Thoughts (Strange Cargo Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Fractal Encounter 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic & Unchained - State Of Discretion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Fractopia (Upspoken Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & CTho - Bad Vibes.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Inner Thoughts (Distant Memories Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Ambrosia Mystic (Dark Heart Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - War Machine (Shifting Complexity Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirl 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Zylot - Passion Flower.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Cortex (Spiritual Visions Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Serpent.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Supernova 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss and Rovastar - The Chaos Of Colours (sprouting diment.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Waves Of Blood.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & StudioMusic - More Cherished Desires.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Greenland.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Explosive Minds.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor & Aderrasi - Canon.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Symmetry.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - glowsticks v2 03 music.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Aieeeeee!!!.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Bitterfeld (Crystal Border Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirlie 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Idiot - Memories Of The Castle.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar and Unchained - Braindance Visions.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Starfish 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Kalideostars (Round  Round Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - The Chaos Of Colours.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cruzin'.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - High Dynamic Range.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - Switching Polygons.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bass Kaleidosphere.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Xen Traffic.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Rovastar - Snowflake Return.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/idiot - Sinful Code (unchained style).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Frozen Rapture .milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Airhandler (Menagerie Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Ultrafast.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rocke - Cold Love (Tei Zwaa).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Triptionary.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Flicker.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Oldskool Mellowstyle.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Che - Escape.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Recirculate (Cool).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Galaxy 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Cranked On Failure.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bipolar 4.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Flicker (@xis).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Illusion - Logic Morph.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bipolar 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and Zylot - Associative Order.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Tschoey - Music Flower.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - Cerebral Demons - Phat + Eo.S. hall of ghouls Remix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Cosmic Mosaic (Active Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Mosaics Of Ages.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - 0 To 60.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Sound And The Fury.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Solar Flare (Reptile).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Feedback 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Planet 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - glowsticks v2 05 and proton lights (+Krash's beat code) _Phat_remix02b.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Fiberglass.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash and Fvese - Molten Indecision (Fvese Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Stranger Minds.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Three Kinds Of Amphetamines.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Brakefreak.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/DaNOnE - Highway to Heaven (rotating).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Microcosm.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - A Million Miles from Earth.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Solar Flare (Blue).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/che - burning hus (oil mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Heavenly 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Hyperion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Eddies 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirlie 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Bow To Gravity.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Rainbow Obscura.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar and Unchained - Life After Pie (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - S Pulse Virus.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Iris.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Heavenly 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Hallucinogenic Pyramids (Beat Time Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Dynamic Fractal (Crazed Spiral Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Reducto Ad Nauseum.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Morat's Final Voyage.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - De La Moutard 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Decreasing Dreams (Extended Movement Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Invariant Under Rigorous Motions.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Crystal Storm.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - A Matter Of Taste (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Resistance.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. + Phat - chasers 18 hallway.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Calligraphy.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Spirit (Twisted Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Rocket.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Wormhole Pillars.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Dark Ritual (Star Of Destiny Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese & Idiot24-7 - Rearview Mirror.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Magic Carpet.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot24-7 - Meeting place.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/PieturP - triptrap_(ultimate-trip-mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bipolar 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EMPR - Random - Changing Polyevolution.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - De La Moutard 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Mstress - Acoustic Nerve Impulses (Under Drug Effetcs (Hypn.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Che - Burning Hus.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Rocke - Headspin.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Dark Subconscious.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Season's Greetings 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Mega Swirl 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/PieturP - triptrap_(getting_concrete_visions_through_a_diafragma_version).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - De(-a)range(d)(ment) strain.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Script.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Ghostlight Whisper.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/shifter - escape the worm - Eo.S. + Phat - Before_It_Eats_Your_Brain_Mix_v2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Pelota De Fuego.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Flower Blossom.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus Fat and Ever Changing.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Chapel Of Ghouls.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - A Million Miles from Earth (Pathfinder Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Inner Thoughts (Clouded Judgement Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Disco Comet.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bass Zoom.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Four Kinds of Amphetamines.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Descent.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Mosaic Waves.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - The Devil Is In The Details.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Bad Karma Oddnezz Style.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Mstress & Juppy - Dancer.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic - Numerosity.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Twisting Indecision.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and che - Inside the House of nil.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Dynamic Fractal 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - De(-a)range(d)(ment) complex.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Starfish 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - A Million Miles From Earth (Wormhole Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic - Twisted Galaxy.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Forgotten Moon.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - All You Can Eat.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Julia Fractal 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 2.3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S.+Phat - Arm_upgrades - transformer.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Smoke.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Causeway Of Dreams (Nightmare Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Xen Traffic.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/illusion & studio music - charged bliss.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Approach.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Inner Thoughts (Dark Secret Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Fractal Encounter.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Hyperspace (Frozen Rapture Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Warp Of Dali 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Songflower (Moss Posy).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness (Duel Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Mstress & Juppy - Dancers In The Dark.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Unchained - Re-Enter Homeworld.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - Altars Of Madness (Mad Ocean Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Unified Drag 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - A Million Miles from Earth (Ripple Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Illusion - Spirit Morph.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Slow Thing (Spiderman Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Zylot - Inside The Planar Portal (Indecision Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Mstress - Celebrate.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Jess - Trying To Trap A Twister.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Cid and Lucy.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Inner Thoughts (Frantic Thoughts Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Toy.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Space.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Floater Society.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Surface.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Redi Jedi - multiple points of origin, one destination.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Studio Music and Unchained - Rapid Alteration.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Corpus Callosum.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Mega Swirl 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Anchorpulse (Pulse Of A Ghast II Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Aderrasi - Oceanic Bassograph (Underwater Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Sunsets.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Non-Professional Music Analyzer.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - heater core C_Phat's_class + sparks_mix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Wisps.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Octotrip.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Contortion (Xenomorph Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Julia Fractal 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Starquake (Sunquake Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Slow Shift Matrix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Digiscape Advanced Processor.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and Rovastar - Altars Of Madness 3 (ooze tweak with .milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Voodoo Chess Magnet (Everglow Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - What cannot be.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Delight (Endless Tunnel Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bonfire.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Texture Boxes (Remix 2).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Che - Adela The Flower (Altars Of Madness Mix 2).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Hyperspace (Hyper Speed Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Bipolar 2 (Vectrip Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EMPR - Random - Turbulence Sandwich.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Che - Asylum Animations.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Vortex 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Antique Abyss.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and Idiot - Any Other Deep Rising.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - light of the path.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Blender.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Centre Of Gravity.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Mstress - Toxic Storm On Acid Sea (The End Of The W.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot & Zylot - Unhealthy Love (Idiot's STDs Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - twisted bytes.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Rovastar - Cerebral Demons (Distant Memory Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Unclaimed Wreckage.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Dynamic Fractal 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Constant Velocity.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Telek - Altars of Madness (Rolling Oceans Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Quicksand.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Airs (Windy Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Candy Avian.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/shifter - escape the worm - Eo.S. + Phat 5362.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Blasto.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Spokes (More Dynamic).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Omnipresence Resurrection (Raw Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - ventilation.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Casino.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Dark Matter (Converse Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Zylot - Sea Of Zigrot.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/idiot - Some big word I learned.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Dreamcatcher.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Cartoon Factory.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic & Unchained - Wrenched Fate.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Lifesavor Anyone.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Downward Spiral.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Can't Stop the Cramming.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - The Chaos Of Colours (Drifting Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss & Rovastar - The Chaos Of Colours (sprouting dimentia mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Shift.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Che - Watch & Fly.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Chromatic Abyss (The Other Side).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Voyage Of Twisted Soul.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Biohazard Warning.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Picture Of Nectar.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss & Rovastar - Notions Of Tonality 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Pulse.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot & Che - Various Abstract Effects.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Ribald Ballad.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Antidote (Side Effects Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Tangent Universe (Collapsed With Artifact Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S.+Phat Cool Bug v2 + (Krash's beat detection).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Vortex of Vortices.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Krash - Cerebral Demons.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Flower.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness (Surealist Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Anomaly 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Stand Still!.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Hovering.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Directive Swagger (Spectral Inferno) (fix...) maybe.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - 9-7-02 (Remix) (sustain fixed).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EMPR - Random - Look mama I'm on TV! 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Spillswirl.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Davod The Pod.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/che - terracarbon stream.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Slow Solstice.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirlie 5.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Festive.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/TobiasWolfBoi - The Pit.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Pinch.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Deadly Flower.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/idiot - Nucleus.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Swirlie 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Pandora's Volcano.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Smoking Delusion Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion - Figure Eight.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Asymptote.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Volume Zoom.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Che - Oddnezz 4 (Done it again).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Digital Smoke.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Dynamic Swirls 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Kalideostars.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Feedback.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Demonic Distortion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Madness Within The Void (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - repeater 15 - kaleidoscope b.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Jaded Emotion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Inkblot.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Planet 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Fvese - Stranger Minds (Astral Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - 3D Shapes Demo.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/[Ishan] - Life in the drains.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Monotone Ripples.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Galaxy 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Fractopia (Galaxy Swirl Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor & Rovastar - Oozing Resistance (Waveform Mod).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Space (Twisted Dimension Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Potion of Spirits.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Krash - Extremophile.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Krash - Interwoven (Contra Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Spirit.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Rush.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzer & Zylot - Force Field Generator (Slowtime Tweak).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Attacking Freedom.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Redi Jedi - acid in your brain.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/fiShbRaiN - blueprint.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Snapshot Of Space.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Custom Gramatix (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor & Che - Inside The House Of Nil.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Antidote (Aqualung Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Sea Shells.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Reenen - phoenix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus Blue.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - God Of The Game (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Dynamic Borders 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Oddball World.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Dynamic Swirls 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness 2 (Frozen Time Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Picture Of Exile.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Tornado.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Supernova 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Luz.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Multiverse Starfield 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Telek - Cosmic Fireworks.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Studio Music - Cherished Desires.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Three And A Half Kinds Of Amphetamines.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Jaundice.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus Gold.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Aimless (Spirogravity Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot and Rovastar - Iouo Stone Morphic Fusion.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Arise! (Padded Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Che - Oddnezz 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Fractopia (Upspoken Mix)_Phat_Speak_When_Spoken_2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Color Of Music.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Illusion - Shifting Sphere.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Painful Plasma (Multi-Wave Mirrored Rage) -- Ro.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - A Blur.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Music Box.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Journey.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cosmic Dust 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Sinews 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - El Cubismo.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Che - Return Of The King.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & TEcHNO - Rhythmic Mantas.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Spiral Tabletop (New and Improved!).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - VooV's Movement (After Dark Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Sine Wave.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Zylot - Azirphaeli's Plan (Multiplan Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - New meetings.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Runoff.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Digital Flame.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Rovastar - Clouded Bottle.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Rocke - Answer.42 (Trippy S. Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Smoke Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Unchained - Demonology (Vampire Soul Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Perverted Dialect.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Idiot24-7 - Balk Acid.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Target Practice (tracking retreat slide).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Azirphaeli's Mirror.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Framed Geometry.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Bmelgren - Godhead.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Krash - Flowing Synergy.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Octotrip (MultiTrip Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Tentacle Dreams (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Clouded Judgement 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 2.2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Inside The Planar Portal.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Harlequin's Maddess.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Nautilus.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/idiot - Spectrum.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Che - The Piper.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Subjective Experience Of The Manifold.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Destruction.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Timeless Voyage.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Broken Destiny Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness (Boxfresh Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Idiot24-7 - Mixed Emotions (Harlequin's Shame Mi.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Slow Shift Matrix (bb4.5).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Vortex 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Deeper Logic.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Global Earthquake.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Bmelgren & Krash - Rainbow Orb Peacock (Lonely Signal Gone .milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & StudioMusic - Twisted Spider Web.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - For The Seagull.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Cosmic Echoes 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Quasilinear Submanifolds.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Picture Of Poison.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Scary.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Games With Light & Sound.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss & Rovastar - Tokamak (Naked Intrusion Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and Rovastar - Altars Of Madness 3 (ooze tweak).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix - www.eos4life.com.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Madness (A Million Miles From Earth Mi.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Mega Swirl 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - The Shroomery.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash and Rovastar - Rainbow Orb.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Solar Flare.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - String.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Rovastar - Snowflake Delight.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek EMPR - Scanner - Trust me I've got a Melways.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash & Illusion - Indecisive Mosaic.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Harlequin's Dynamic Fractal (Dual Spiral Mix ).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Warp Of Dali Bright.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - heater core C_Phat's_on route_mix+beam.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EvilJim - Follow the ball.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Parallel Universe.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EvilJim - Ice Drops.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Antidote.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/EMPR - Random - They're so cute Dad can I keep one!.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Making Time (Swamp Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Block Of Sound (Abstract Architecture Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Coral.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Free to Feel (Valium Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Altars Of Harlequin's Madness (Dark Disorder Mix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Tripmaker.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Working the Grid.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Unchained - Invade My Mind.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - simple.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Rovastar - Crystal Ball (Cerimonial Decor Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/idiot - Nothing Yet - 03 - The worst of the pack.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Drift.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cosmic Dust 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/nil - Singularity in My Oscilloscope.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Octopus Gold with Dots.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Bellanova (New Wave Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Diffraction.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion & Unchained - Frozen Eye 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor and StudioMusic - Vertigyny (Geiss shape mod).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Causeway Of Dreams.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - The Deeper.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/CrystalHigh - mad ravetriping.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Cosmic Echoes 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Multiverse Starfield 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - The Fatty Lumpkin Sunkle Tweaker.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Aimless (Gravity Directive Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Dynamic Swirls 3 (Poltergiest Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Eo.S. - repeater 05 - rave on acid.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Crystal Ball (Magical Reaction Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Zylot - Narell's Fever.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Illusion - Heavenly Eye.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Cosmic Havoc.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Tube.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Circlefacade.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Reducto Absurdum.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Mixing Pot.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Sinews 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic - It's Only Make Believe.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - The Inner Workings of my New Computer.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Octoplasm.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Flowing Form.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - VooV's Movement.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Dark Ritual (Star Of Destiny Denied Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss & Rovastar - Julia Fractal (Vectrip Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cepiasound.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar and Krash - Hallucinogenic Pyramids (Extra Beat Ti.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Bmelgren - Take This Highway.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Beat Demo 1.0.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - ReAwoke.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Cycloid 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/TEcHNO and SandStorm - Psychodelic Highway.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Idiot24-7 - Mixed Emotions (Harlequin's Shame Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bipolar 5.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Spacedust.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bright Fiber Matrix 1.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot & Aderrasi - Oceanic Bassograph (New Jersey Shore Mix.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic & Unchained - So Much Love.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - What Cannot Be Undone.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Pistons.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Warp Of Dali 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Krash - Windowframe To Mega Swirl 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Block Of Sound (Fractal Construction Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Solarized Space (Space DNA Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - Typomatic (Remix 2).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Future Speakers.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - Zoom Effects (Remix 2).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Zylot - Visionarie (geiss aspect ratio fix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Telek - Lost Star (Flash).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Goo Kung Fu.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Fvese - The Tunnel (Final Stage Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar - Halcyon Dreams 3.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Shaping The Grid.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mi.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Space Voyage.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - MOTIVATION!.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Shake.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Ashes Of Air (Remix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Eggs.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Bmelgren - Pentultimate Nerual Slipstream (Tweak 2).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Waterfall.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Idiot - What Shall Come.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Bright Fiber Matrix 2.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Aderrasi - Anchorpulse (Verified Mix).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rozzor - Learning Curve (Invert tweak).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Unchained - Unclaimed Wreckage 2 (Shamanic).milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss - Tokamak.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rocke - Personal Comet.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Geiss - Ice Planet.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/StudioMusic & Unchained - Entity.milk"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Geiss & Sperl - Feedback (projectM idle HDR mix).prjm"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Rovastar & Sperl - Tuxflower.prjm"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/project.tga"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/Tux.tga"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/M.tga"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/presets/headphones.tga"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/spiff/kode/visualization.projectm/lib/libprojectM/NONE/share/projectM/fonts" TYPE FILE FILES
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/fonts/VeraMono.ttf"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/fonts/Vera.ttf"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/spiff/kode/visualization.projectm/lib/libprojectM/NONE/lib/pkgconfig" TYPE FILE FILES "/home/spiff/kode/visualization.projectm/lib/libprojectM/libprojectM.pc")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "/home/spiff/kode/visualization.projectm/lib/libprojectM/NONE/share/projectM" TYPE FILE FILES "/home/spiff/kode/visualization.projectm/lib/libprojectM/config.inp")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/libprojectM" TYPE FILE FILES
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/projectM.hpp"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/event.h"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/dlldefs.h"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/fatal.h"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/PresetFrameIO.hpp"
    "/home/spiff/kode/visualization.projectm/lib/libprojectM/PCM.hpp"
    )
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/home/spiff/kode/visualization.projectm/lib/libprojectM/libprojectM.a")
ENDIF(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/home/spiff/kode/visualization.projectm/lib/libprojectM/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/home/spiff/kode/visualization.projectm/lib/libprojectM/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
