#
#
# Try to find the PROJECTM libraries
# Once done this will define
#
# PROJECTM_FOUND          - system has projectM
# PROJECTM_INCLUDE_DIR    - path to libprojectM/projectM.hpp
# PROJECTM_LIBRARY      - the library that must be included
#
#

IF (PROJECTM_LIBRARY AND PROJECTM_INCLUDE_DIR)
  SET(PROJECTM_FOUND "YES")
ELSE (PROJECTM_LIBRARY AND PROJECTM_INCLUDE_DIR)
  FIND_PATH(PROJECTM_INCLUDE_DIR projectM.hpp PATHS /usr/local/include/libprojectM /usr/include/libprojectM)
  FIND_LIBRARY(PROJECTM_LIBRARY projectM PATHS /usr/local/lib /usr/lib)
  
  IF (PROJECTM_INCLUDE_DIR AND PROJECTM_LIBRARY)
    SET(PROJECTM_FOUND "YES")
  ELSE (PROJECTM_INCLUDE_DIR AND PROJECTM_LIBRARY)
    SET(PROJECTM_FOUND "NO")
  ENDIF (PROJECTM_INCLUDE_DIR AND PROJECTM_LIBRARY)
ENDIF (PROJECTM_LIBRARY AND PROJECTM_INCLUDE_DIR)

IF (PROJECTM_FOUND)
  MESSAGE(STATUS "Found PROJECTM libraries at ${PROJECTM_LIBRARY} and includes at ${PROJECTM_INCLUDE_DIR}")
ELSE (PROJECTM_FOUND)
  IF (PROJECTM_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find PROJECTM libraries")
  ENDIF (PROJECTM_FIND_REQUIRED)
ENDIF (PROJECTM_FOUND)
